apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: cards-payment-service
  labels:
    app: cards-payment-service
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: cards-payment-service
  minReplicas: 3
  maxReplicas: 12
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 70
