apiVersion: v1
kind: ConfigMap
metadata:
  name: cards-enterprise-api-service
  labels:
    app: cards-enterprise-api-service
data:
  SERVER_PORT: "8085"
  SPRING_APPLICATION_NAME: cards-enterprise-api-service
