apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: cards-enterprise-api-service
  labels:
    app: cards-enterprise-api-service
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: cards-enterprise-api-service
