apiVersion: v1
kind: Service
metadata:
  name: cards-enterprise-api-service
  labels:
    app: cards-enterprise-api-service
spec:
  type: ClusterIP
  selector:
    app: cards-enterprise-api-service
  ports:
    - name: http
      port: 8085
      targetPort: http
