apiVersion: v1
kind: Service
metadata:
  name: cards-authentication-service
  labels:
    app: cards-authentication-service
spec:
  type: ClusterIP
  selector:
    app: cards-authentication-service
  ports:
    - name: http
      port: 8081
      targetPort: http
