apiVersion: apps/v1
kind: Deployment
metadata:
  name: cards-api-gateway-service
  labels:
    app: cards-api-gateway-service
spec:
  replicas: 3
  selector:
    matchLabels:
      app: cards-api-gateway-service
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: cards-api-gateway-service
    spec:
      terminationGracePeriodSeconds: 40
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              podAffinityTerm:
                labelSelector:
                  matchLabels:
                    app: cards-api-gateway-service
                topologyKey: kubernetes.io/hostname
      containers:
        - name: cards-api-gateway-service
          image: cards-api-gateway-service:1.0.0
          ports:
            - name: http
              containerPort: 8080
          envFrom:
            - configMapRef:
                name: cards-api-gateway-service
            - secretRef:
                name: cards-api-gateway-service
          resources:
            requests:
              cpu: 250m
              memory: 512Mi
            limits:
              cpu: 1000m
              memory: 1Gi
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: http
            initialDelaySeconds: 40
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: http
            initialDelaySeconds: 20
            periodSeconds: 5
