apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: cards-notification-service
  labels:
    app: cards-notification-service
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: cards-notification-service
