apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: cards-platform
resources:
  - namespace.yaml
  - cards-authentication-service
  - cards-account-details-service
  - cards-payment-service
  - cards-notification-service
  - cards-enterprise-api-service
  - cards-bff-dashboard-service
  - cards-api-gateway-service
