apiVersion: v1
kind: ConfigMap
metadata:
  name: cards-account-details-service
  labels:
    app: cards-account-details-service
data:
  SERVER_PORT: "8082"
  SPRING_APPLICATION_NAME: cards-account-details-service
  DB_URL: jdbc:postgresql://postgres.cards-platform.svc.cluster.local:5432/account_db
