apiVersion: v1
kind: Service
metadata:
  name: cards-account-details-service
  labels:
    app: cards-account-details-service
spec:
  type: ClusterIP
  selector:
    app: cards-account-details-service
  ports:
    - name: http
      port: 8082
      targetPort: http
